// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRtiYn4T83I19cjnGn1cSVNlRLfzdV5TA',
    appId: '1:892044250518:web:57ca79d363846f9c62a1b7',
    messagingSenderId: '892044250518',
    projectId: 'employee-db-e464a',
    authDomain: 'employee-db-e464a.firebaseapp.com',
    databaseURL: 'https://employee-db-e464a-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-e464a.firebasestorage.app',
    measurementId: 'G-PVJ19Q82SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpAeeVU19TWLwgWotTvl9tQV15rwji-k',
    appId: '1:892044250518:android:6adc47fc815135b862a1b7',
    messagingSenderId: '892044250518',
    projectId: 'employee-db-e464a',
    databaseURL: 'https://employee-db-e464a-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-e464a.firebasestorage.app',
  );
}
